### ISSUE TITLE
Incorrect "omit" flag

### ISSUE THREAD

**Issue by apertome** [perfsonar/psconfig-web#103]
PWA is setting an `omit-interval` test parameter, but it should just be `omit`.

**Comment by mfeit-internet2** [comment]
AJ brought this to my attention.  The value produced for the JSON should be an ISO 8601 duration, e.g., `PT5S`.

**Comment by apertome** [comment]
Thanks for clarifying that, Mark!

**Comment by apertome** [comment]
Fixed, and pushed to dockerhub
