### ISSUE TITLE
perfsonar-psconfig-web-admin-api.service Failing to start

### ISSUE THREAD

**Issue by shaunmarchant** [perfsonar/psconfig-web#145]
New install on Centos7 with perfsonar-centralmanagement, psconfig-web-admin-api wont stay active. Have added hostname of system and installed via yum.

> ● perfsonar-psconfig-web-admin-api.service - perfSONAR PWA API daemon
>    Loaded: loaded (/usr/lib/systemd/system/perfsonar-psconfig-web-admin-api.service; enabled; vendor preset: disabled  )
>    Active: failed (Result: start-limit) since Fri 2019-11-08 13:49:10 GMT; 2s ago
>   Process: 3337 ExecStart=/usr/bin/node api/pwaadmin.js (code=exited, status=1/FAILURE)
>  Main PID: 3337 (code=exited, status=1/FAILURE)
> 
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: perfsonar-psconfig-web-admin-api.service: main process exited, code...ILURE
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: Unit perfsonar-psconfig-web-admin-api.service entered failed state.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: perfsonar-psconfig-web-admin-api.service failed.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: perfsonar-psconfig-web-admin-api.service holdoff time over, schedul...tart.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: Stopped perfSONAR PWA API daemon.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: start request repeated too quickly for perfsonar-psconfig-web-admin...rvice
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: Failed to start perfSONAR PWA API daemon.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: Unit perfsonar-psconfig-web-admin-api.service entered failed state.
> Nov 08 13:49:10 perfSonar-CTL systemd[1]: perfsonar-psconfig-web-admin-api.service failed.

**Comment by apertome** [comment]
@boaz-raz is seeing something similar.

**Comment by boaz-raz** [comment]
It is working fine for me when using perfSONAR-repo-nightly-minor-0.9-1.noarch.rpm 
From http://software.internet2.edu/rpms/el7/x86_64/latest/packages/

**Comment by stanier** [comment]
Is there going to be a fix for this soon or should we just be running with the nightly for the time being?
