### ISSUE TITLE
Improve how slip is handled

### ISSUE THREAD

**Issue by apertome** [perfsonar/psconfig-web#175]
Slip is not being handled in an intelligent way; I'm not sure if there's a default value, and maybe we can automatically calculate a default slip based on the test interval or something. The UI also needs improvements to more clearly state the significance of slip. We should also review sliprand.

**Comment by mfeit-internet2** [comment]
pScheduler's default slip value is none.  The CLI forces `PT5M` if you don't provide one on the assumption that if you're running an ad hoc test, you want to find time for it to run.  The API intentionally does _not_ do that.

**Comment by apertome** [comment]
@mfeit-internet2 : A default value of "none" means it won't allow any slip, right? In which case if people don't set something reasonable, they'll likely have a lot of nonstarters.

Probably a good topic to discuss in more depth on the Monday call.

**Comment by apertome** [comment]
On a call last week we agreed that the default slip should be a percentage of the test interval ... perhaps 100%, and `sliprand` should be enabled. moving forward with those assumptions.
