### ISSUE TITLE
Add Keep After Archive for Tasks

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/psconfig-web#224]
For 5.0.0, a new task parameter called `keep-after-archive` has been added that governs how long runs are kept after the last archiving is complete.  (See [pscheduler/#1071.)](https://github.com/perfsonar/pscheduler/issues/1071).)

The value is an ISO 8601 duration.  If not set, the parameter should not be present in the generated task specification.

The task's `schema` must be set to at least `5` if this parameter is present.

Per discussion:  Add this to each test entry in config section.

Sample JSON:

```
{
    "schema": 5,  <----- NEW
    "archives": [
        ...
    ],
    "keep-after-archive": "PT30S",    <----- NEW
    "test": {
        ...
    }
}
```

**Comment by grigutis** [comment]
0f4f35fe600dafb82d45d30cf731a3ca74d44c35 resolves this issue.
