### ISSUE TITLE
REST API doc not accessible using https://hostname/pwa/apidoc/

### ISSUE THREAD

**Issue by skulambi** [perfsonar/psconfig-web#225]
Hi,

I am able to use PWA for configuration purpose works fine, but the link for apidoc is not working using below link -

https://192.168.122.99/pwa/apidoc/ which is mentioned in http://docs.perfsonar.net/pwa_api.html

Is there any other configuration which is required to access the REST API documentation?

Thanks

**Comment by skulambi** [comment]
What I observed was the 'assets' folder from source code 'psconfig-web/ui/apidoc/assets' is missing after the PWA is installation on the target (/usr/lib/perfsonar/psconfig-web-admin/ui/ui/apidoc - 'assets' folder missing here) which is causing the issue. After copying the 'assets' folder was able to access the REST API documentation.

**Comment by ksandeep-palc** [comment]
Raised a PR - https://github.com/perfsonar/psconfig-web/pull/226

**Comment by grigutis** [comment]
Accepted. Thank you!

**Comment by ksandeep-palc** [comment]
Thanks @grigutis !!
