### ISSUE TITLE
Dependency issue for perfsonar-psconfig-web-admin-auth-4.4.5-1.el7.x86_64 on RHEL7

### ISSUE THREAD

**Issue by alexdodson** [perfsonar/psconfig-web#228]
Hello,

The update for this package is breaking updates to our pwa host. The version required of libstdc++ seems different than the version available in rhel7

--> Finished Dependency Resolution
Error: Package: perfsonar-psconfig-web-admin-auth-4.4.5-1.el7.x86_64 (Internet2)
           Requires: libstdc++.so.6(CXXABI_1.3.8)(64bit)
Error: Package: perfsonar-psconfig-web-admin-auth-4.4.5-1.el7.x86_64 (Internet2)
           Requires: libstdc++.so.6(GLIBCXX_3.4.21)(64bit)
Error: Package: perfsonar-psconfig-web-admin-auth-4.4.5-1.el7.x86_64 (Internet2)
           Requires: libstdc++.so.6(CXXABI_1.3.9)(64bit)

Here is the info on the installed version

$ yum info libstdc++
Loaded plugins: priorities, versionlock
105 packages excluded due to repository priority protections
Installed Packages
Name        : libstdc++
Arch        : x86_64
Version     : 4.8.5
Release     : 44.el7
Size        : 1.0 M
Repo        : installed
From repo   : rhel7-x86_64-updates
Summary     : GNU Standard C++ Library
URL         : http://gcc.gnu.org
License     : GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions and LGPLv2+ and BSD
Description : The libstdc++ package contains a rewritten standard compliant GCC Standard
            : C++ Library.
            
Any ideas on how we can resolve this?

Thanks,
Alex

**Comment by topper59** [comment]
Can confirm this issue on OL7, tried it quickly on CentOS 7 and had the same result. I ended up using OL8 and manually installing dependencies and the RPMs

**Comment by alexdodson** [comment]
Hello,

We are using RHEL7. A quick search to fulfill the requirements for libstdc++.so.6(CXXABI_1.3.9)(64bit) shows only two repos available, one being ghettoforge and the other an nvidia cuda repo. https://pkgs.org/download/libstdc++.so.6(CXXABI_1.3.9)(64bit) .  A google shows it could be an issue with the node version so I have included them below as well.

The node versions we have installed are from EPEL

yum list installed | grep nodejs
nodejs.x86_64                     1:16.17.0-1.el7      @epel                    
nodejs-libs.x86_64                1:16.17.0-1.el7      @epel

**Comment by alexdodson** [comment]
The packages for libstdc++ match for centos7 and rhel7 as well.

**Comment by grigutis** [comment]
This is actually a problem with [sca-auth](https://github.com/perfsonar/sca-auth). It is fixed in the 5.0.0 branch, but [I added a commit to fix it in the 4.4.5 branch as well](https://github.com/perfsonar/sca-auth/commit/a4e1afa5fb66399557b61060e358258fa11910cd). I'm still struggling to get that new rpm built correctly, but hopefully you should see a fix soon.

**Comment by grigutis** [comment]
A new build has been pushed to the repo, so this should now be fixed.
