### ISSUE TITLE
No way to delete user accounts?

### ISSUE THREAD

**Issue by ShawnMcKee** [perfsonar/psconfig-web#32]
Can we have a way to delete users / groups?

I couldn't find a way to do that?

Shawn

**Comment by soichih** [comment]
You can deactivate user/group, but the activation flag is not used by
various login handler. I will update the authentication service - which is
a shared component that I am still maintaining.

Soichi

**Comment by soichih** [comment]
I've updated the auth service to more uniformly obay "active" flag. Please do "docker pull soichih/sca-auth" and re-run docker container.

**Comment by soichih** [comment]
FYI. Marina pushed my updated to OSG's MCA instances (https://meshconfig.grid.iu.edu).

**Comment by apertome** [comment]
Deleting the user account works. Closing.
