### ISSUE TITLE
too easy to wipe-out a "HOST GROUP" - recipe follows

### ISSUE THREAD

**Issue by rseuster** [perfsonar/psconfig-web#36]
Hi,

just after nuking a host group in the "meshconfig-admin" here:
https://meshconfig.grid.iu.edu
and having it restored by hand, I wanted to report this "feature".

All I did was when looking at a host group to toggle the entry for hosts between "Static" to "Dynamic" and back to "Static". The list of hosts then is/ was empty and the "update" button enabled. I assumed update here means just to reload the page, but it did really update the host group with an empty list of hosts, effectively killing the test.

Could this be looked at ? This is just too easy to wipe out the group of hosts in  meshconfig.

Thanks, Rolf

**Comment by apertome** [comment]
Hi Rolf, this has been fixed in the upcoming release that is coming out along with perfSONAR 4.1 beta 1.

Thanks,
Michael
