### ISSUE TITLE
Add twamp tool

### ISSUE THREAD

**Issue by apertome** [perfsonar/psconfig-web#54]
We need to add the twamp tool (`twping`) to PWA.

I realized this may be a bit of an issue, since the latency tests PWA generates are all `latencybg` whereas `twping` needs to run as `latency`

**Comment by vvidic** [comment]
On Wed, May 23, 2018 at 02:12:43PM -0700, Michael Johnson wrote:
> We need to add the twamp tool (`twping`) to PWA.
> 
> I realized this may be a bit of an issue, since the latency tests PWA
> generates are all `latencybg` whereas `twping` needs to run as
> `latency`

Yes, we don't have powstream equivalent for twamp yet.

But if we get RTT variant of twping working maybe it would be
easier to add it a twping rtt test instead (as an alternative
to ping).

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by apertome** [comment]
This is done, waiting to close until we verify it works in the nightly test mesh

**Comment by apertome** [comment]
This is working well in the mesh now, closing.
