### ISSUE TITLE
Problem with the /pub/config publication of mesh includes

### ISSUE THREAD

**Issue by ShawnMcKee** [perfsonar/psconfig-web#58]
There is a problem with PWA when trying to gather the list of mesh configs using the /pub/config interface.  This is breaking our MaDDash at http://psmad.opensciencegrid.org.

To see the problem, try accessing https://psconfig.aglt2.org/pub/config

The URLs returned in the JSON look like:

include: [
"https://http://psconfig.opensciencegrid.org/pub/config/us-atlas"
]

Notice 'https://http://...'

If you go to the http version it is still broken:

You get 'http://http://...'

Thanks,
Shawn

**Comment by apertome** [comment]
Shawn tells me this is fixed now.
