### ISSUE TITLE
rpm packaging for pwa

### ISSUE THREAD

**Issue by apertome** [perfsonar/psconfig-web#62]
We need to provide deployment models other than docker, specifically RPM. I think we would want .deb packaging as well.

Ideally I would do this before the PWA 4.2 (first non-beta PWA) release.

**Comment by apertome** [comment]
I'd like to try to get this done for 4.2 but not sure yet:

- whether it's a requirement
- how involved this will be

**Comment by apertome** [comment]
Much of the initial packaging is done, adding subtickets for a couple other items

**Comment by vvidic** [comment]
On Wed, Apr 03, 2019 at 09:09:12AM -0700, Michael Johnson wrote:
> Much of the initial packaging is done, adding subtickets for a couple other items

Great, you think I can try something on the Debian side of things?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by apertome** [comment]
@vvidic Yes, let me wrap up a couple things and then I will add this to Jenkins, which I think will help us build the node stuff, and make it easier for you to see the build process on the centos side -- unless you have another suggestion for how to handle it. We could meet and discuss too if that would be helpful.

**Comment by vvidic** [comment]
On Wed, Apr 03, 2019 at 06:50:54PM +0000, Michael Johnson wrote:
> @vvidic Yes, let me wrap up a couple things and then I will add this
> to Jenkins, which I think will help us build the node stuff, and make
> it easier for you to see the build process on the centos side --
> unless you have another suggestion for how to handle it. We could meet
> and discuss too if that would be helpful.

I don't have much experience with nodejs so I probably can't help
there, but it would be nice if the dependencies were bundled like
in the graphs repo so we ship exactly the same js code on both
ends. 

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by apertome** [comment]
Yes I have some of that happening already, and I'm working toward getting the other components built and packaged.

**Comment by vvidic** [comment]
On Wed, Apr 03, 2019 at 06:56:50PM +0000, Michael Johnson wrote:
> Yes I have some of that happening already, and I'm working toward
> getting the other components built and packaged.

Thanks, that sounds perfect :)  I'm away this week, but will try to
check it when I get back.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
