### ISSUE TITLE
https vs http

### ISSUE THREAD

**Issue by ajragusa** [perfsonar/psconfig-web#74]
I'm not sure if this is a bug or just a misconfiguration.  We have a mesh config that was generated using PWA that is a bit confused about https vs. http.  Some hosts read/write URLs are http and some hosts read/write URLs are https.  Only the https ones work, and we have to manually go through and fix the hosts that are http -> https.

**Comment by apertome** [comment]
I have reached out to the users who reported this, and not received any response; I believe it's been addressed. Will reopen if I get more information.
