### ISSUE TITLE
Do not set display-url to 'auto' in pSConfig format

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig-web#75]
pSConfig does not support a value of "auto" since the agent tries not to make assumptions about things such as the format of the URL. PWA should fill it in with the toolkit URL by default (which leads to the same result). It would also be nice if we had a way to determine if the host in question is actually a toolkit (As opposed to a test point or similar without the page). This should be in the LS, not sure how hard it would be to integrate in the GUI.

**Comment by apertome** [comment]
@arlake228 can you review this?

Full example; note that I"m autogenerating https URLs since most people use SSL; we could make it generate http: urls instead:

http://mca-nightly.grnoc.iu.edu/pub/config/testbed-nightly?format=psconfig

**Comment by arlake228** [comment]
This looks perfect to me and can be closed when you are ready.
