### ISSUE TITLE
Ability to import pSConfig format

### ISSUE THREAD

**Issue by arlake228** [perfsonar/psconfig-web#76]
From a user:

> When I try to import your mesh JSON file at http://icnmgmt0.internet2.edu/psconfig/osg_stashcache_templates.json  I get this exception:
> 
> 1|pwaadmin | Thu Dec 06 2018 14:54:42 GMT+0000 (UTC) - error: Thu, 06 Dec 2018 14:54:42 GMT uncaughtException: Cannot read property 'forEach' of undefined
> 1|pwaadmin | Thu Dec 06 2018 14:54:42 GMT+0000 (UTC) - error: TypeError: Cannot read property 'forEach' of undefined
> 1|pwaadmin |     at Object.exports._process_imported_config (/app/api/admin/controllers/importer.js:206:29)
> 1|pwaadmin |     at Request._callback (/app/api/admin/controllers/importer.js:168:17)
> 1|pwaadmin |     at Request.self.callback (/app/node_modules/request/request.js:185:22)
> 1|pwaadmin |     at emitTwo (events.js:106:13)
> 1|pwaadmin |     at Request.emit (events.js:191:7)
> 1|pwaadmin |     at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
> 1|pwaadmin |     at emitOne (events.js:96:13)
> 1|pwaadmin |     at Request.emit (events.js:188:7)
> 1|pwaadmin |     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
> 1|pwaadmin |     at IncomingMessage.g (events.js:292:16)
> 1|pwaadmin |     at emitNone (events.js:91:20)
> 1|pwaadmin |     at IncomingMessage.emit (events.js:185:7)
> 1|pwaadmin |     at endReadableNT (_stream_readable.js:974:12)
> 1|pwaadmin |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
> 1|pwaadmin |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
> 
> It is likely that there are bugs in PWA and I don't believe the mesh config imported was checked or modified much from the original MCA implementation.

**Comment by apertome** [comment]
The issue here is that ironcially, PWA does not know how to import pSConfig templates, only MeshConfig format.

**Comment by apertome** [comment]
We have the ability to import psconfig format now, but `disjoint` meshes are not supported. There is a separate ticket for tracking that functionality, #129
